### ISSUE TITLE
Liquid nitrogen level and the progress bar

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_GridClipping#16]
I think the progress bar to indicates the level of the liquid nitrogen?

Why do you need it? You have the surface showing the level in the workstation. You have already told the player to fill the nitrogen to a certain level. Why can not you stop/hint when the level reaches the correct position?

**Comment by chenyingjie** [comment]
Now I know the function of progress bar. Better change it to .. Please wait for xx minute to cool down the workstation.

Also, the current position of the progress bar is right behind the liquid nitrogen tank while I pour the nitrogen into the work station. Better move the progress bar a little bit higher.

**Comment by Wandayu** [comment]
In version 1.04, because people use the right hand more often to pour liquid nitrogen, the progress bar was moved to the left side to reduce the possibility of obscuring it. But the exact position may need more comments and testing.
![v1 04_ProgressBar](https://user-images.githubusercontent.com/31882005/102843491-4c2d5100-43d7-11eb-98a6-3736649d8f57.png)

**Comment by smallelephant9516** [comment]
The progress bar is not blocked currently.
