### ISSUE TITLE
Hand gesture is not correct when using the clip tools

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#6]
When pushing the cap of the clip tools in the step of assembling the clip ring and grids, it should be the thumb press the top instead of just grab it.

**Comment by Wandayu** [comment]
Existing interaction is the left-hand holding the insertion tool with the right hand approaching the plunger and moving downward, without the need to press the trigger to perform the grabbing action.

![Hand Gesture_PressPlunger](https://user-images.githubusercontent.com/31882005/101404404-96291980-38a4-11eb-95fb-c754313faba5.png)

Considering that the triggers of each hand are used to implement the grabbing function, and that two hands can not be too close to each other due to the physical size of the controllers and their detection, this issue requires further discussion.

**Comment by smallelephant9516** [comment]
The gesture of holding the clip tool sometimes is not correct in step 18, it should be the thumb on the top of the tool, it does not happen very often.
![image](https://user-images.githubusercontent.com/52638056/101427972-e2d51a80-38cd-11eb-9c09-0f21e852eda7.png)
